version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "docker-sam-practice"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vjv8oeadrb1q"
s3_prefix = "docker-sam-practice"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []